# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96632842893c3f39c8944d30cf6fe57d24f6f9c49bcb8ec89ca888f9a74aea8c9ff7af87a4cefd940ec7671c99c538d799f4b349b907f63ae3fdf42060cb5ecc

test:
  secret_key_base: 5b0e01b1c8615b302021ada2528adfb708cfb3dd95f7eb13fb2cad38e273bf641839c2b27ea2e6127bb4a140e6422436b6fa46387c4ac752f13612dc792fe0ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
